import 'package:orbitvision/modals/planate_modals.dart';

List<CelestialBody> SolarSystem = [
  CelestialBody(
    name: "Mercury",
    Planet: "Planet",
    distanceFromSun: 0.39,
    orbitalPeriod: 0.24,
    orbitalSpeed: 47.87,
    imageUrl: "assets/image/Mercury.gif",
    slogen: "Mercury is the smallest and innermost planet in the Solar System.",
    hero: 'Mercury',
    file: 'assets/3D/Mercury.glb',
    image: 'assets/image/Mercury.png',
    descriptione:
        'From the surface of Mercury, the Sun would appear more than three times as large as it does when viewed from Earth, and the sunlight would be as much as 11 times brighter.',
    surfacearea: '74.8 million km²',
    satellites: '0',
  ),
  CelestialBody(
    name: "Venus",
    Planet: "Planet",
    hero: 'Venus',
    distanceFromSun: 0.72,
    orbitalPeriod: 0.62,
    orbitalSpeed: 35.02,
    imageUrl: "assets/image/Venus.gif",
    slogen:
        "Venus is the second planet from the Sun and is often called Earth's 'sister planet'.",
    file: 'assets/3D/Venus.glb',
    descriptione:
        "Similar in structure and size to Earth, Venus's thick atmosphere traps heat in a runaway greenhouse effect, making it the hottest planet in our solar system.",
    image: 'assets/image/Venus.png',
    surfacearea: '460.2 million km²',
    satellites: '0',
  ),
  CelestialBody(
    name: "Earth",
    Planet: "The Blue Planet",
    hero: 'Earth',
    distanceFromSun: 1.0,
    orbitalPeriod: 1.0,
    orbitalSpeed: 29.78,
    imageUrl: "assets/image/Earth.gif",
    slogen:
        "Earth is the third planet from the Sun and the only planet known to support life.",
    file: 'assets/3D/Earth.glb',
    descriptione:
        "Earth—our home planet—is the only place we know of so far that’s inhabited by living things. It's also the only planet in our solar system with liquid water on the surface.",
    image: 'assets/image/Earth.png',
    surfacearea: '510.1 million km²',
    satellites: '1',
  ),
  CelestialBody(
    name: "Moon",
    hero: 'Moon',
    distanceFromSun: 1.0,
    orbitalPeriod: 27.3,
    orbitalSpeed: 1.0,
    imageUrl: "assets/image/Moon.gif",
    slogen: "The Moon is Earth's only natural satellite.",
    file: 'assets/3D/Moon.glb',
    descriptione:
        'The Moon is thought to have formed about 4.5 billion years ago, not long after Earth.',
    image: 'assets/image/Moon.png',
    Planet: 'MOON',
    surfacearea: '4.6 million km²',
    satellites: '0',
  ),
  CelestialBody(
    name: "Mars",
    Planet: "Planet",
    hero: 'Mars',
    distanceFromSun: 1.52,
    orbitalPeriod: 1.88,
    orbitalSpeed: 24.077,
    imageUrl: "assets/image/Mars.gif",
    slogen:
        "Mars is often called the 'Red Planet' due to its reddish appearance.",
    file: 'assets/3D/Mars.glb',
    descriptione:
        'Mars is a dusty, cold, desert world \n with a very thin atmosphere. There is strong evidence Mars was – billions of years ago – wetter and warmer, with a thicker atmosphere.',
    image: 'assets/image/Mars.png',
    surfacearea: '144.8 million km²',
    satellites: '2',
  ),
  CelestialBody(
    name: "Jupiter",
    Planet: "Planet",
    hero: 'Jupiter',
    distanceFromSun: 5.20,
    orbitalPeriod: 11.86,
    orbitalSpeed: 13.07,
    imageUrl: "assets/image/Jupiter.gif",
    slogen:
        "Jupiter is the largest planet in our solar system and is known for its massive size.",
    file: 'assets/3D/Jupiter.glb',
    descriptione:
        "Jupiter is more than twice as massive than the other planets of our solar system combined. The giant planet's Great Red spot is a centuries-old storm bigger than Earth.",
    image: 'assets/image/Jupiter.png',
    surfacearea: '61.42 billion km²',
    satellites: '79',
  ),
  CelestialBody(
    name: "Saturn",
    Planet: "Planet",
    hero: 'Saturn',
    distanceFromSun: 9.58,
    orbitalPeriod: 29.46,
    orbitalSpeed: 9.69,
    imageUrl: "assets/image/Saturn.gif",
    slogen:
        "Saturn is recognized by its stunning ring system, composed of icy particles and debris.",
    file: 'assets/3D/Saturn.glb',
    descriptione:
        "Adorned with a dazzling, complex system of icy rings, Saturn is unique in our solar system. The other giant planets have rings, but none are as spectacular as Saturn's.",
    image: 'assets/image/Saturn.png',
    surfacearea: '42.7 billion km²',
    satellites: '82',
  ),
  CelestialBody(
    name: "Uranus",
    Planet: "Planet",
    hero: 'Uranus',
    distanceFromSun: 19.22,
    orbitalPeriod: 84.01,
    orbitalSpeed: 6.81,
    imageUrl: "assets/image/Uranus.gif",
    slogen:
        "Uranus is unique due to its rotation being tilted almost perpendicular to its orbit.",
    file: 'assets/3D/Uranus.glb',
    descriptione:
        'Uranus—seventh planet from the Sun—rotates at a nearly 90-degree angle from the plane of its orbit. This unique tilt makes Uranus appear to spin on its side.',
    image: 'assets/image/Uranus.png',
    surfacearea: '8.08 billion km²',
    satellites: '27',
  ),
  CelestialBody(
    name: "Neptune",
    Planet: "Planet",
    hero: 'Neptune',
    distanceFromSun: 30.05,
    orbitalPeriod: 164.79,
    orbitalSpeed: 5.43,
    imageUrl: "assets/image/Neptune.gif",
    slogen:
        "Neptune is the eighth and farthest known planet from the Sun, and is an icy giant.",
    file: 'assets/3D/Neptune.glb',
    descriptione:
        'Neptune—the eighth and most distant major planet orbiting our Sun—is dark, cold and whipped by supersonic winds. It was the first planet located through mathematical calculations.',
    image: 'assets/image/Neptune.png',
    surfacearea: '7.62 billion km²',
    satellites: '14',
  ),
  CelestialBody(
    name: "Sun",
    hero: 'Sun',
    distanceFromSun: 0.0,
    orbitalPeriod: 0.0,
    orbitalSpeed: 0.0,
    imageUrl: "assets/image/Sun.png",
    slogen: "The Sun is the star at the center of the Solar System.",
    file: 'assets/3D/Sun.glb',
    descriptione:
        'The Sun is a nearly perfect sphere of hot plasma, with internal convective motion generating a magnetic field via a dynamo process.',
    image: 'assets/image/Sun.png',
    Planet: 'Sun',
    surfacearea: '695 x 106 million km²',
    satellites: '0',
  ),
];
